// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsuagnsttvnshtullkdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdWFnbnN0dHZuc2h0dWxsa2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjkwMzIsImV4cCI6MjA2OTcwNTAzMn0.MRCQb0tCTfD4rl-4zoQyBJGL2oOSPtImEgAWx3vOyKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});